### ISSUE TITLE
Font request: black blocks

### ISSUE THREAD

**Issue by chrissam42** [chrissam42/font-variant-wut#1]
Would like to try a version of the font that behaves the same way as now, but instead of replacing the feature tag with a `{tagg}`, just replace it with a plain black block. This could be used to create a machine-readable "bar code" of features that are enabled/disabled by the various switches.

**Comment by djrrb** [comment]
so all features look the same?

**Comment by djrrb** [comment]
e8316bc552780ae7aa2dbf26354552b950f8a4db
